apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: alidns-operator 
  namespace: {{ .Values.namespace }} 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alidns-operator 
rules:
- apiGroups: [""] 
  resources: ["events","pods","services","endpoints","secrets"]
  verbs: ["*"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch"] 
  resources: ["cronjobs"]
  verbs: ["*"]
- apiGroups: ["tools.newesis.com"]
  resources: ["alidns"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: alidns-operator 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: ClusterRole 
  name: alidns-operator
subjects: 
  - kind: ServiceAccount 
    name: alidns-operator 
    namespace: {{ .Values.namespace }}