FROM python:3.7 
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
  && rm -rf /var/lib/apt/lists/*
RUN wget --quiet https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip \
  && unzip terraform_0.14.5_linux_amd64.zip \
  && rm terraform_0.14.5_linux_amd64.zip
RUN chmod +x terraform
RUN pip install docopt && pip install requests && pip install pyopenssl && pip install requests-toolbelt
COPY alidnsmanager.py /alidnsmanager.py 
COPY aliprivezone.tf /aliprivezone.tf
WORKDIR /
CMD python alidnsmanager.py
